name: Docker Image CI


on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "franckccv" --password-stdin
        docker image build -t franckccv/window_update_attack:1.0 .
        docker push franckccv/window_update_attack:1.0
